/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Frequencia;
import beans.Funcionario;
import eventos.AlterarFrequenciaHandler;
import eventos.ButtonHandlerVoltarFrequencia;
import eventos.GerarRelatorioFrequenciaMesFuncionarioHandler;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import service.RelatorioFrequenciaFuncionario;
import service.UtilDatas;

/**
 *
 * @author Gilmar
 */
public class ListarFrequencia extends javax.swing.JFrame {

    /**
     * Creates new form ListarFrequencia
     */
    
    
        public JTable getTable(){
        return jTable1;
    }
    public void setTable(JTable jTable) {
          jTable1 = jTable; 
          System.out.println("Setou o Table");
    }
    
    private List<Frequencia> frequencias;

    public List<Frequencia> getFrequencias() {
        return frequencias;
    }
    
    public ListarFrequencia(String[] args, List<Frequencia> frequencias) {
        initComponents();
        setLocationRelativeTo(null);
        this.frequencias = frequencias;
        Integer mes;
        Integer ano;
        String[] split = new String[3];
        System.out.println(frequencias.get(0).getData().toString());
        split = frequencias.get(0).getData().toString().split("-");
        System.out.println(split.length);
        mes = Integer.valueOf(split[1]);
        ano = Integer.valueOf(split[0]);
        GerarRelatorioFrequenciaMesFuncionarioHandler gerarRelatorioFrequenciaMesFuncionarioHandler = new GerarRelatorioFrequenciaMesFuncionarioHandler(mes, ano, frequencias);
        jButton3.addActionListener(gerarRelatorioFrequenciaMesFuncionarioHandler);
        ButtonHandlerVoltarFrequencia buttonHandlerVoltarFrequencia = new ButtonHandlerVoltarFrequencia(this);
        jButton1.addActionListener(buttonHandlerVoltarFrequencia);
        AlterarFrequenciaHandler alterarFrequenciaHandler = new AlterarFrequenciaHandler(this);
        jButton2.addActionListener(alterarFrequenciaHandler);
//        JTable jTable = new JTable();
        DefaultTableModel model = new DefaultTableModel();
        jTable1.setModel(model);
        Funcionario funcionario = new Funcionario();
        
               
        model.addColumn("Data");
        model.addColumn("Manhã");
        model.addColumn("Horário de Saída");
        model.addColumn("Tarde");
        model.addColumn("Horário de Saída");
        
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        List<Frequencia> util = new ArrayList<Frequencia>();
        
        for(Frequencia frequencia : frequencias){
            
        	model.addRow(new Object[]{UtilDatas.DateToString(frequencia.getData()), frequencia.getFuncionario().getNome(), frequencia.getFuncionario().getPortaria(), RelatorioFrequenciaFuncionario.getFrequenciaString(frequencia.getPresenca())});
        }
//        jTable1 = jTable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1035, 690));
        setMinimumSize(new java.awt.Dimension(1035, 690));
        setPreferredSize(new java.awt.Dimension(1035, 690));
        setResizable(false);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Data", "Nome", "Portaria", "Presença"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(15);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(15);
        jTable1.getColumnModel().getColumn(3).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(15);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 190, 670, 280);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/back.png"))); // NOI18N
        jButton1.setText("Voltar");
        getContentPane().add(jButton1);
        jButton1.setBounds(630, 490, 140, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/Editar.png"))); // NOI18N
        jButton2.setText("Editar Presença");
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 490, 140, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Frequência Mensal");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(470, 100, 160, 17);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/tarjaGovernoAzul.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1080, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/ok.png"))); // NOI18N
        jButton3.setText("Emitir Relatório");
        jButton3.setMaximumSize(new java.awt.Dimension(81, 25));
        jButton3.setMinimumSize(new java.awt.Dimension(81, 25));
        jButton3.setPreferredSize(new java.awt.Dimension(81, 25));
        getContentPane().add(jButton3);
        jButton3.setBounds(450, 490, 140, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/backgroundBlueClaro3.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 140, 770, 420);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/backgroundBlue.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMinimumSize(new java.awt.Dimension(1024, 700));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(final String args[], final List<Frequencia> frequencias) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarFrequencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarFrequencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarFrequencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarFrequencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarFrequencia(args, frequencias).setVisible(true);
                System.out.println("MAIN");
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
