/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Funcionario;
import eventos.ApagarUsuarioHandler;
import eventos.ButtonHandlerVoltarPesquisarUsuario;
import eventos.PesquisarUsuarioButtonHandler;
import eventos.SelecionarUsuarioHandler;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import negocio.UsuarioLogado;
import java.awt.Color;

/**
 *
 * @author Gilmar
 */
public class ProcurarUsuario extends javax.swing.JFrame {

    private Funcionario[] funcionarios;
    
    
    
            /**
     * Creates new form ListarUsuario
     */
    
    public String TextFiel1(){
        return jTextField1.getText();
    }
    
    public void setJTextField1(String valorTF){
        jTextField1.setText(valorTF);
    }
    
    public JTable getTable(){
        return jTable1;
    }
    public void setTable(JTable jTable) {
          jTable1 = jTable;
    }

    private ProcurarUsuario() {
        initComponents();
        JOptionPane.setRootFrame(this);
        setLocationRelativeTo(null);
        PesquisarUsuarioButtonHandler pesquisarUsuarioButtonHandler = new PesquisarUsuarioButtonHandler(this);
        jButton1.addActionListener(pesquisarUsuarioButtonHandler);
        ButtonHandlerVoltarPesquisarUsuario voltarPesquisarUsuarioHandler = new ButtonHandlerVoltarPesquisarUsuario(this);
        jButton4.addActionListener(voltarPesquisarUsuarioHandler);
        SelecionarUsuarioHandler selecionarUsuarioHandler = new SelecionarUsuarioHandler(this);
        jButton2.addActionListener(selecionarUsuarioHandler);
        ApagarUsuarioHandler apagarUsuarioHandler = new ApagarUsuarioHandler(this);
        jButton3.addActionListener(apagarUsuarioHandler);
        jLabel6.setText("Bem vindo, " + UsuarioLogado.getInstancia().getUsuarioLogado().getNome().toUpperCase().split(" ")[0]);

//        jButton3.addActionListener(pesquisarUsuarioButtonHandler);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel1.setBounds(0, 0, 1050, 25);
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setBounds(180, 278, 645, 200);
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setBounds(195, 221, 120, 15);
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setBounds(315, 216, 160, 27);
        jButton1 = new javax.swing.JButton();
        jButton1.setBounds(495, 213, 130, 30);
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setBounds(180, 187, 470, 80);
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setBounds(310, 620, 410, 15);
        jButton2 = new javax.swing.JButton();
        jButton2.setBounds(269, 489, 120, 30);
        jButton3 = new javax.swing.JButton();
        jButton3.setBounds(461, 489, 120, 30);
        jButton4 = new javax.swing.JButton();
        jButton4.setBounds(659, 489, 120, 30);
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setBounds(651, 151, 160, 15);
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setBounds(120, 140, 760, 420);
        jLabel7 = new javax.swing.JLabel();
        jLabel7.setBounds(-23, 0, 1060, 680);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("ListarUsuario"); // NOI18N
        setResizable(false);
        setMinimumSize(new java.awt.Dimension(1024, 700));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/tarjaGovernoAzul.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(102, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Data de Admissão", "Portaria", "Salário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(3).setResizable(false);

        getContentPane().add(jScrollPane1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(Color.GRAY);
        jLabel3.setText("Nome do Usuário: ");
        getContentPane().add(jLabel3);
        getContentPane().add(jTextField1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/procurar.png"))); // NOI18N
        jButton1.setText("Pesquisar");
        getContentPane().add(jButton1);

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 102, 102)));
        getContentPane().add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Copyright © 2014 Virtua Softwares. Todos os direitos reservados.");
        getContentPane().add(jLabel5);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/Editar.png"))); // NOI18N
        jButton2.setText("Editar");
        getContentPane().add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/cancel_10x10.png"))); // NOI18N
        jButton3.setText("Excluir");
        getContentPane().add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/back.png"))); // NOI18N
        jButton4.setText("Voltar");
        getContentPane().add(jButton4);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Bem Vindo, ");
        getContentPane().add(jLabel6);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/backgroundBlueClaro3.jpg"))); // NOI18N
        getContentPane().add(jLabel2);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/backgroundBlue.jpg"))); // NOI18N
        jLabel7.setAutoscrolls(true);
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel7.setMaximumSize(new java.awt.Dimension(1024, 700));
        jLabel7.setMinimumSize(new java.awt.Dimension(1024, 700));
        getContentPane().add(jLabel7);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcurarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcurarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcurarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcurarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcurarUsuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
